name: Build Android App Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android AAB with Capacitor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Sync Capacitor
        run: npx cap sync android
        working-directory: ./frontend

      - name: Copy web assets to Android
        run: npx cap copy android
        working-directory: ./frontend

      - name: Build Android AAB
        run: ./gradlew bundleRelease
        working-directory: android

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
