# .github/workflows/android-build.yml
name: Android APK Build with Capacitor

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend

      - name: Build frontend
        run: yarn build
        working-directory: ./frontend

      - name: Capacitor Sync
        run: npx cap sync android
        working-directory: ./frontend

      - name: Copy assets to Android
        run: npx cap copy android
        working-directory: ./frontend

      - name: Build Android APK
        run: ./gradlew assembleRelease
        working-directory: ./frontend/android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: PotBot-APK
          path: ./frontend/android/app/build/outputs/apk/release/app-release.apk
