name: Build Android APK

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          cd frontend
          yarn install

      - name: Build React App
        run: |
          cd frontend
          yarn build

      - name: Sync Capacitor
        run: |
          cd frontend
          npx cap sync

      - name: Build APK
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: frontend/android
          gradle-task: assembleRelease
          output-path: frontend/android/app/build/outputs/apk/release/app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PotBot-APK
          path: frontend/android/app/build/outputs/apk/release/app-release.apk
