name: Build Android AAB with Capacitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies with NPM
        run: npm install --legacy-peer-deps
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Sync Capacitor
        run: npx cap sync android
        working-directory: ./frontend

      - name: Copy Capacitor assets
        run: npx cap copy android
        working-directory: ./frontend

      - name: Build Android AAB
        run: ./gradlew bundleRelease
        working-directory: ./frontend/android

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: frontend/android/app/build/outputs/bundle/release/app-release.aab