name: Build Android Debug APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: frontend/android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: PotBot-APK
          path: frontend/android/app/build/outputs/apk/debug/app-debug.apk