name: Build Signed Android APK

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > $HOME/keystore.jks

      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Build React App
        working-directory: ./frontend
        run: yarn build

      - name: Sync Capacitor
        working-directory: ./frontend
        run: npx cap sync

      - name: Make Gradle Executable
        run: chmod +x ./frontend/android/gradlew

      - name: Build Signed APK
        working-directory: ./frontend/android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PotBot-Signed-APK
          path: frontend/android/app/build/outputs/apk/release/app-release.apk
